# Generated by Django 5.1.2 on 2024-11-14 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('brand', models.CharField(default='متفرقه', max_length=50, verbose_name='برند')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='اسلاگ')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('image', models.ImageField(blank=True, upload_to='images/products/', verbose_name='تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='موجود')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='حذف')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
    ]
