# Generated by Django 5.1.2 on 2024-11-15 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'آیتم', 'verbose_name_plural': 'آیتم ها'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='order_address',
        ),
    ]
