# Generated by Django 5.1.2 on 2024-11-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_address',
            new_name='shipping_address',
        ),
    ]
