# Generated by Django 5.1.2 on 2024-11-15 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_order_address_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='track_number',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
