# Generated by Django 5.1.2 on 2024-11-17 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_rename_price_orderitem_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total_cost',
        ),
    ]
