# Generated by Django 5.1.2 on 2024-11-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_remove_orderitem_total_cost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_price',
            new_name='price',
        ),
    ]
